'use client'

import { useState } from 'react'
import { ArrowRight, Check, ChevronRight, CircleAlert, FileText, LockKeyhole, Menu, Mic, ReceiptIndianRupee, ShieldCheck, UserRound, Waves, X, Zap } from 'lucide-react'

type Service = 'grievance' | 'tax'

type ImpactItem = { number: string; title: string; question: string; description: string; reality: string; icon: typeof CircleAlert }

const impact: ImpactItem[] = [
  { number: '01', title: 'Target audience', question: 'Who is facing the problem?', description: 'Semi-urban citizens, rural farmers, and gig-economy workers navigating critical public services.', reality: 'The barrier is not internet access. It is the severe gap in English-centric digital literacy and complex form navigation.', icon: UserRound },
  { number: '02', title: 'Legacy system bottlenecks', question: 'What is difficult about the current experience?', description: 'Information asymmetry, rigid dropdown classification systems, and heavy legal and financial terminology.', reality: 'Legacy portals rely on cascading dropdowns. A wrong department or misunderstood code creates instant rejection cycles.', icon: FileText },
  { number: '03', title: 'Core architectural intervention', question: 'What did we change?', description: 'Localized natural language and visual parsing engines replace manual semantic input pipelines.', reality: 'Unstructured native speech or passbook images are translated, normalized, and mapped into government-compliant schemas.', icon: Zap },
  { number: '04', title: 'Measurable efficiency outcomes', question: 'Why is this version better?', description: 'Drastic reduction in cognitive load, structural validation errors, and administrative routing delays.', reality: 'Server-side intent classification removes navigation errors. Conversational checkpoints prevent failures before final ingestion.', icon: Check },
  { number: '05', title: 'Engineering boundaries', question: 'What works today, and what is still mocked?', description: 'End-to-end user state machine execution with active AI pipelines versus isolated sandbox environments.', reality: 'LIVE: multilingual transcription, intent parsing, and visual extraction. MOCKED: database commits, Aadhaar OTP, and ministry API writes.', icon: ShieldCheck },
  { number: '06', title: 'Production scale & security protocols', question: 'How could this work safely at scale?', description: 'PII scrubbing, edge token management, and optimized payload compression for low-bandwidth networks.', reality: 'Client-side anonymization masks Aadhaar and PAN before processing. Lightweight audio codecs keep rural connections responsive.', icon: LockKeyhole },
]

function Logo() { return <div className="landing-logo"><span><Waves /></span><b>nagrik</b></div> }

function AuthModal({ service, close, enter }: { service: Service; close: () => void; enter: () => void }) {
  const [value, setValue] = useState(''); const [loading, setLoading] = useState(false)
  const proceed = () => { setLoading(true); window.setTimeout(enter, 900) }
  return <div className="modal-backdrop" onMouseDown={close}><div className="auth-modal" role="dialog" aria-modal="true" aria-labelledby="auth-title" onMouseDown={e => e.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close"><X /></button><div className="auth-icon"><ShieldCheck /></div><span className="kicker">SANDBOX ACCESS</span><h2 id="auth-title">A secure start for every citizen.</h2><p>Use any demo identity to preview the {service === 'tax' ? 'tax portal' : 'grievance router'}.</p><label htmlFor="identity">Aadhaar number or mobile number</label><input id="identity" value={value} onChange={e => setValue(e.target.value.replace(/[^0-9]/g, '').slice(0, 12))} placeholder="e.g. 98765 43210" inputMode="numeric" /><div className="bypass"><Zap /><span><b>Demo access enabled</b><br />Enter any 12 digits, or leave this blank.</span></div><button className="auth-submit" onClick={proceed} disabled={loading}>{loading ? 'Verifying securely...' : <>Verify & proceed <ArrowRight /></>}</button><small className="modal-foot"><LockKeyhole /> No identity data is stored</small></div></div>
}

function ImpactSection() { return <section className="impact-section" id="impact"><div className="section-intro"><div><span className="kicker">SYSTEM NOTES</span><h2>Designed around the reality<br />of public service.</h2></div><p>A technical assessment of the barriers, interventions, and safeguards behind nagrik.</p></div><div className="impact-grid">{impact.map(({ number, title, question, description, reality, icon: Icon }) => <article className="impact-card" key={number}><div className="impact-card-top"><span className="impact-number">{number}</span><Icon /></div><span className="impact-label">{title}</span><h3>{question}</h3><p>{description}</p><div className="reality"><span>TECHNICAL REALITY</span><p>{reality}</p></div></article>)}</div></section> }

function Landing({ launch }: { launch: (service: Service) => void }) { return <main className="landing"><div className="government-bar"><span><ShieldCheck /> Government of India · Hackathon Sandbox Division</span><span>Build What Moves India 2026 <ChevronRight /></span></div><nav className="landing-nav"><Logo /><div className="nav-links"><a href="#impact">System notes</a><a href="#how">How it works</a><button onClick={() => launch('grievance')}>Evaluator access <ArrowRight /></button></div><button className="mobile-menu" aria-label="Open navigation"><Menu /></button></nav><section className="hero"><div className="hero-copy"><div className="hero-label"><span className="pulse" /> Citizen-first digital infrastructure</div><h1>Public services that <em>understand</em> people.</h1><p>Reimagining Indian public infrastructure for 1.4 billion citizens — with voice, clarity, and dignity built in.</p><div className="hero-actions"><button className="hero-primary" onClick={() => launch('grievance')}><CircleAlert /> Launch grievance router <ArrowRight /></button><button className="hero-secondary" onClick={() => launch('tax')}><ReceiptIndianRupee /> Launch conversational tax portal</button></div></div><div className="hero-visual"><div className="phone"><div className="phone-top"><span className="nagrik-mark">nagrik</span><span>● secure</span></div><div className="phone-greeting">Good morning, Rajesh <span>नमस्ते</span></div><div className="phone-question">How can we help today?</div><div className="phone-option"><CircleAlert /><span><b>Report a grievance</b><small>Speak in your own words</small></span><ChevronRight /></div><div className="phone-option"><ReceiptIndianRupee /><span><b>File your taxes</b><small>Answer a few simple questions</small></span><ChevronRight /></div></div><div className="floating-notification floating-notification-en"><div className="notification-icon"><ShieldCheck /></div><div><strong>Grievance received</strong><span>We&apos;ll keep you updated via SMS</span></div><Check /></div><div className="floating-notification floating-notification-hi"><div className="notification-icon"><CircleAlert /></div><div><strong>मेरी पाइपलाइन टूट गई है</strong><span>आपकी शिकायत दर्ज हो गई है</span></div><Check /></div></div></section><ImpactSection /><section className="how-section" id="how"><div><span className="kicker">ONE CLEAR PATH</span><h2>From intent to outcome.</h2></div><div className="process"><div><b>01</b><span>Speak or upload</span></div><ChevronRight /><div><b>02</b><span>We understand</span></div><ChevronRight /><div><b>03</b><span>You take action</span></div></div></section><footer className="landing-footer"><Logo /><span>Built for access, designed for dignity.</span><span>Demo environment · 2026</span></footer></main> }

function Dashboard({ service, setService, exit }: { service: Service; setService: (s: Service) => void; exit: () => void }) { return <main className="dashboard"><aside className="dash-side"><Logo /><span className="kicker">YOUR SERVICES</span><button className={service === 'grievance' ? 'selected' : ''} onClick={() => setService('grievance')}><CircleAlert /> Grievance Router</button><button className={service === 'tax' ? 'selected' : ''} onClick={() => setService('tax')}><ReceiptIndianRupee /> Tax Portal</button><div className="side-bottom"><div><ShieldCheck /> Demo data only.<br />Nothing is stored or sent.</div><button onClick={exit}><UserRound /> Rajesh Kumar</button></div></aside><section className="dash-main"><header className="dash-header"><div><span className="kicker">{service === 'tax' ? 'CONVERSATIONAL TAX PORTAL' : 'VOICE-FIRST CIVIC SERVICE'}</span><h1>{service === 'tax' ? 'Taxes, without the tax-speak.' : 'Let’s get that sorted.'}</h1></div><button onClick={exit} className="exit-button">Exit demo <ArrowRight /></button></header><div className="dash-content"><div className="demo-panel"><div className="panel-label">{service === 'tax' ? 'YOUR TAX INTERVIEW' : 'TELL US WHAT HAPPENED'}</div><div className="demo-center"><div className="demo-mic"><Mic /></div><h2>{service === 'tax' ? 'How do you earn your money?' : 'Tap to record your grievance'}</h2><p>{service === 'tax' ? 'Pick the option that feels most like you.' : 'Speak naturally in Hindi, Tamil, Hinglish, or English.'}</p><button className="demo-action">{service === 'tax' ? 'Start interview' : 'Start recording'} <ArrowRight /></button></div></div><div className="dash-aside"><div className="panel-label">WHY NAGRIK</div><h3>Built for clarity, not compliance.</h3><p>Every interaction is designed to reduce cognitive load and return agency to the citizen.</p><div className="check-line"><Check /> Multilingual by default</div><div className="check-line"><Check /> Voice-first and accessible</div></div></div></section></main> }

export default function Page() { const [auth, setAuth] = useState<Service | null>(null); const [entered, setEntered] = useState(false); const [service, setService] = useState<Service>('grievance'); if (entered) return <Dashboard service={service} setService={setService} exit={() => setEntered(false)} />; return <><Landing launch={setAuth} />{auth && <AuthModal service={auth} close={() => setAuth(null)} enter={() => { setService(auth); setAuth(null); setEntered(true) }} />}</> }
